# Phase 2: Data Exploration — Decathlon Data Analytics

## Objective

The objective of this phase is to understand the structure, quality, and characteristics of the Decathlon sales database before performing detailed analysis.

## Tasks

1. Connect to the SQL Server database.
2. Load the products, sales, and store tables.
3. Understand the number of rows and columns.
4. Inspect column names and data types.
5. Check missing values and duplicate records.
6. Identify potential data quality issues.
7. Explore numerical and categorical columns.
8. Review possible relationships between tables.
9. Summarize the findings for the next phase.

**Tools:** Python, Pandas, NumPy, Matplotlib, Seaborn, SQL Server.

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from IPython.display import display
from src.database import get_connection

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:,.2f}".format)

sns.set_theme(style="whitegrid")

print("Libraries imported successfully.")

Libraries imported successfully.

### Connect to SQL Server

In [6]:
conn = get_connection()

print("Connected to DecathlonDB successfully.")

Connected to DecathlonDB successfully.

### Check available tables

In [7]:
tables_query = """
SELECT
    TABLE_SCHEMA,
    TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_SCHEMA, TABLE_NAME;
"""

tables_df = pd.read_sql_query(tables_query, conn)

display(tables_df)

C:\Users\nasir\AppData\Local\Temp\ipykernel_3724\3277697516.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tables_df = pd.read_sql_query(tables_query, conn)

  TABLE_SCHEMA TABLE_NAME
0          dbo   products
1          dbo      sales
2          dbo      store

### Load the three tables

In [8]:
products_query = "SELECT * FROM dbo.products"
sales_query = "SELECT * FROM dbo.sales"
store_query = "SELECT * FROM dbo.store"

products_df = pd.read_sql_query(products_query, conn)
sales_df = pd.read_sql_query(sales_query, conn)
store_df = pd.read_sql_query(store_query, conn)

print("All tables loaded successfully.")

print(f"Products: {products_df.shape[0]:,} rows")
print(f"Sales:    {sales_df.shape[0]:,} rows")
print(f"Stores:   {store_df.shape[0]:,} rows")

C:\Users\nasir\AppData\Local\Temp\ipykernel_3724\2658503984.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  products_df = pd.read_sql_query(products_query, conn)
C:\Users\nasir\AppData\Local\Temp\ipykernel_3724\2658503984.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  sales_df = pd.read_sql_query(sales_query, conn)

All tables loaded successfully.
Products: 240 rows
Sales:    84,000 rows
Stores:   30 rows

C:\Users\nasir\AppData\Local\Temp\ipykernel_3724\2658503984.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  store_df = pd.read_sql_query(store_query, conn)

### Preview the datasets

In [9]:
print("PRODUCTS DATA")
display(products_df.head())

print("SALES DATA")
display(sales_df.head())

print("STORE DATA")
display(store_df.head())

PRODUCTS DATA

,Product_Key,Product_Name,Sport,Product_Type,Brand_Label,Product_Tier,Colour,Base_List_Price_INR,Base_Unit_Cost_INR
0,P0001,Running Shoes Essential Black (Demo),Running,Running Shoes,Kalenji,Essential,Black,"1,599.00","1,012.00"
1,P0002,Running Shoes Essential Blue (Demo),Running,Running Shoes,Kalenji,Essential,Blue,"1,799.00","1,102.00"
2,P0003,Running Shoes Active Black (Demo),Running,Running Shoes,Kalenji,Active,Black,"1,999.00","1,050.00"
3,P0004,Running Shoes Active Blue (Demo),Running,Running Shoes,Kalenji,Active,Blue,"2,299.00","1,559.00"
4,P0005,Running Shoes Performance Black (Demo),Running,Running Shoes,Kalenji,Performance,Black,"2,799.00","1,768.00"

SALES DATA

,Sale_Line_ID,Order_ID,Purchase_Date,Product_ID,Store_ID,Channel,Payment_Method,Order_Hour,Promotion,Quantity,Unit_List_Price_INR,Unit_Cost_INR,Discount_Pct,Gross_Sales_INR,Discount_INR,Sales_Before_Returns_INR,Returned_Qty,Refund_INR,Net_Sales_INR,Net_COGS_INR,Gross_Profit_INR,Return_Reason
0,SL000001,ORD000001,2025-01-01,P0193,S030,In Store,UPI,19,None,1,799.00,515.00,0%,799.00,0.00,799.00,0,0.00,799.00,515.00,284.00,Not Returned
1,SL000002,ORD000001,2025-01-01,P0111,S030,In Store,UPI,19,None,1,299.00,178.00,0%,299.00,0.00,299.00,0,0.00,299.00,178.00,121.00,Not Returned
2,SL000003,ORD000001,2025-01-01,P0211,S030,In Store,UPI,19,None,1,199.00,112.00,0%,199.00,0.00,199.00,0,0.00,199.00,112.00,87.00,Not Returned
3,SL000004,ORD000002,2025-01-01,P0065,S001,In Store,Credit Card,20,None,1,999.00,547.00,0%,999.00,0.00,999.00,0,0.00,999.00,547.00,452.00,Not Returned
4,SL000005,ORD000002,2025-01-01,P0223,S001,In Store,Credit Card,20,None,2,399.00,216.00,0%,798.00,0.00,798.00,0,0.00,798.00,432.00,366.00,Not Returned

STORE DATA

,Store_Key,Store_Name,City,State,Region,Country,Store_Format,Floor_Area_Sqm
0,S001,Demo Mumbai Sports Store,Mumbai,Maharashtra,West,India,Large Format,4900
1,S002,Demo Pune Sports Store,Pune,Maharashtra,West,India,Standard,3800
2,S003,Demo Nashik Sports Store,Nashik,Maharashtra,West,India,Standard,2600
3,S004,Demo Nagpur Sports Store,Nagpur,Maharashtra,West,India,Standard,2400
4,S005,Demo Ahmedabad Sports Store,Ahmedabad,Gujarat,West,India,Large Format,1900

### Understand dataset dimensions

In [10]:
dataset_summary = pd.DataFrame({
    "Dataset": ["Products", "Sales", "Stores"],
    "Rows": [
        products_df.shape[0],
        sales_df.shape[0],
        store_df.shape[0]
    ],
    "Columns": [
        products_df.shape[1],
        sales_df.shape[1],
        store_df.shape[1]
    ]
})

display(dataset_summary)

    Dataset   Rows  Columns
0  Products    240        9
1     Sales  84000       22
2    Stores     30        8

### Inspect column names

In [11]:
datasets = {
    "Products": products_df,
    "Sales": sales_df,
    "Stores": store_df
}

for name, df in datasets.items():
    print(f"\n{name.upper()} COLUMN NAMES")
    print(df.columns.tolist())

PRODUCTS COLUMN NAMES
['Product_Key', 'Product_Name', 'Sport', 'Product_Type', 'Brand_Label', 'Product_Tier', 'Colour', 'Base_List_Price_INR', 'Base_Unit_Cost_INR']

SALES COLUMN NAMES
['Sale_Line_ID', 'Order_ID', 'Purchase_Date', 'Product_ID', 'Store_ID', 'Channel', 'Payment_Method', 'Order_Hour', 'Promotion', 'Quantity', 'Unit_List_Price_INR', 'Unit_Cost_INR', 'Discount_Pct', 'Gross_Sales_INR', 'Discount_INR', 'Sales_Before_Returns_INR', 'Returned_Qty', 'Refund_INR', 'Net_Sales_INR', 'Net_COGS_INR', 'Gross_Profit_INR', 'Return_Reason']

STORES COLUMN NAMES
['Store_Key', 'Store_Name', 'City', 'State', 'Region', 'Country', 'Store_Format', 'Floor_Area_Sqm']

### Inspect data types

In [12]:
for name, df in datasets.items():
    print(f"\n{name.upper()} DATA TYPES")
    df.info()

PRODUCTS DATA TYPES
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Product_Key          240 non-null    object
 1   Product_Name         240 non-null    object
 2   Sport                240 non-null    object
 3   Product_Type         240 non-null    object
 4   Brand_Label          240 non-null    object
 5   Product_Tier         240 non-null    object
 6   Colour               240 non-null    object
 7   Base_List_Price_INR  240 non-null    float64
 8   Base_Unit_Cost_INR   240 non-null    float64
dtypes: float64(2), object(7)
memory usage: 17.0+ KB

SALES DATA TYPES
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84000 entries, 0 to 83999
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Sale_Line_ID              84000 non-null  object
 1   Order_ID                  84000 non-null  object
 2   Purchase_Date             84000 non-null  object
 3   Product_ID                84000 non-null  object
 4   Store_ID                  84000 non-null  object
 5   Channel                   84000 non-null  object
 6   Payment_Method            84000 non-null  object
 7   Order_Hour                84000 non-null  int64
 8   Promotion                 84000 non-null  object
 9   Quantity                  84000 non-null  int64
 10  Unit_List_Price_INR       84000 non-null  float64
 11  Unit_Cost_INR             84000 non-null  float64
 12  Discount_Pct              84000 non-null  object
 13  Gross_Sales_INR           84000 non-null  float64
 14  Discount_INR              84000 non-null  float64
 15  Sales_Before_Returns_INR  84000 non-null  float64
 16  Returned_Qty              84000 non-null  int64
 17  Refund_INR                84000 non-null  float64
 18  Net_Sales_INR             84000 non-null  float64
 19  Net_COGS_INR              84000 non-null  float64
 20  Gross_Profit_INR          84000 non-null  float64
 21  Return_Reason             84000 non-null  object
dtypes: float64(9), int64(3), object(10)
memory usage: 14.1+ MB

STORES DATA TYPES
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Store_Key       30 non-null     object
 1   Store_Name      30 non-null     object
 2   City            30 non-null     object
 3   State           30 non-null     object
 4   Region          30 non-null     object
 5   Country         30 non-null     object
 6   Store_Format    30 non-null     object
 7   Floor_Area_Sqm  30 non-null     int64
dtypes: int64(1), object(7)
memory usage: 2.0+ KB

### Create a data type summary

In [13]:
for name, df in datasets.items():
    dtype_summary = pd.DataFrame({
        "Column": df.columns,
        "Data_Type": df.dtypes.astype(str).values,
        "Non_Null_Count": df.notna().sum().values,
        "Missing_Count": df.isna().sum().values
    })

    print(f"\n{name.upper()} DATA TYPE SUMMARY")
    display(dtype_summary)

PRODUCTS DATA TYPE SUMMARY

                Column Data_Type  Non_Null_Count  Missing_Count
0          Product_Key    object             240              0
1         Product_Name    object             240              0
2                Sport    object             240              0
3         Product_Type    object             240              0
4          Brand_Label    object             240              0
5         Product_Tier    object             240              0
6               Colour    object             240              0
7  Base_List_Price_INR   float64             240              0
8   Base_Unit_Cost_INR   float64             240              0

SALES DATA TYPE SUMMARY

                      Column Data_Type  Non_Null_Count  Missing_Count
0               Sale_Line_ID    object           84000              0
1                   Order_ID    object           84000              0
2              Purchase_Date    object           84000              0
3                 Product_ID    object           84000              0
4                   Store_ID    object           84000              0
5                    Channel    object           84000              0
6             Payment_Method    object           84000              0
7                 Order_Hour     int64           84000              0
8                  Promotion    object           84000              0
9                   Quantity     int64           84000              0
10       Unit_List_Price_INR   float64           84000              0
11             Unit_Cost_INR   float64           84000              0
12              Discount_Pct    object           84000              0
13           Gross_Sales_INR   float64           84000              0
14              Discount_INR   float64           84000              0
15  Sales_Before_Returns_INR   float64           84000              0
16              Returned_Qty     int64           84000              0
17                Refund_INR   float64           84000              0
18             Net_Sales_INR   float64           84000              0
19              Net_COGS_INR   float64           84000              0
20          Gross_Profit_INR   float64           84000              0
21             Return_Reason    object           84000              0

STORES DATA TYPE SUMMARY

           Column Data_Type  Non_Null_Count  Missing_Count
0       Store_Key    object              30              0
1      Store_Name    object              30              0
2            City    object              30              0
3           State    object              30              0
4          Region    object              30              0
5         Country    object              30              0
6    Store_Format    object              30              0
7  Floor_Area_Sqm     int64              30              0

### Check missing values

In [14]:
for name, df in datasets.items():
    print(f"\n{name.upper()} MISSING VALUES")

    missing_summary = pd.DataFrame({
        "Missing_Count": df.isna().sum(),
        "Missing_Percentage": (
            df.isna().sum() / len(df) * 100
            if len(df) > 0
            else 0
        )
    })

    missing_summary = missing_summary.sort_values(
        by="Missing_Percentage",
        ascending=False
    )

    display(missing_summary)

PRODUCTS MISSING VALUES

                     Missing_Count  Missing_Percentage
Product_Key                      0                0.00
Product_Name                     0                0.00
Sport                            0                0.00
Product_Type                     0                0.00
Brand_Label                      0                0.00
Product_Tier                     0                0.00
Colour                           0                0.00
Base_List_Price_INR              0                0.00
Base_Unit_Cost_INR               0                0.00

SALES MISSING VALUES

                          Missing_Count  Missing_Percentage
Sale_Line_ID                          0                0.00
Order_ID                              0                0.00
Purchase_Date                         0                0.00
Product_ID                            0                0.00
Store_ID                              0                0.00
Channel                               0                0.00
Payment_Method                        0                0.00
Order_Hour                            0                0.00
Promotion                             0                0.00
Quantity                              0                0.00
Unit_List_Price_INR                   0                0.00
Unit_Cost_INR                         0                0.00
Discount_Pct                          0                0.00
Gross_Sales_INR                       0                0.00
Discount_INR                          0                0.00
Sales_Before_Returns_INR              0                0.00
Returned_Qty                          0                0.00
Refund_INR                            0                0.00
Net_Sales_INR                         0                0.00
Net_COGS_INR                          0                0.00
Gross_Profit_INR                      0                0.00
Return_Reason                         0                0.00

STORES MISSING VALUES

                Missing_Count  Missing_Percentage
Store_Key                   0                0.00
Store_Name                  0                0.00
City                        0                0.00
State                       0                0.00
Region                      0                0.00
Country                     0                0.00
Store_Format                0                0.00
Floor_Area_Sqm              0                0.00

### Visualize missing values

In [15]:
for name, df in datasets.items():
    missing_counts = df.isna().sum()
    missing_counts = missing_counts[missing_counts > 0]

    if not missing_counts.empty:
        plt.figure(figsize=(10, 5))
        missing_counts.sort_values().plot(kind="barh")

        plt.title(f"Missing Values — {name}")
        plt.xlabel("Number of Missing Values")
        plt.ylabel("Columns")
        plt.tight_layout()
        plt.show()
    else:
        print(f"{name}: No missing values found.")

Products: No missing values found.
Sales: No missing values found.
Stores: No missing values found.

### Check duplicate records

In [16]:
for name, df in datasets.items():
    duplicate_count = df.duplicated().sum()

    print(f"{name}: {duplicate_count:,} duplicate rows")

Products: 0 duplicate rows
Sales: 0 duplicate rows
Stores: 0 duplicate rows

### Display duplicate records

In [17]:
for name, df in datasets.items():
    duplicates = df[df.duplicated(keep=False)]

    print(f"\n{name.upper()} DUPLICATE RECORDS")

    if duplicates.empty:
        print("No duplicate rows found.")
    else:
        display(duplicates.head(10))

PRODUCTS DUPLICATE RECORDS
No duplicate rows found.

SALES DUPLICATE RECORDS
No duplicate rows found.

STORES DUPLICATE RECORDS
No duplicate rows found.

### Generate descriptive statistics

In [18]:
for name, df in datasets.items():
    print(f"\n{name.upper()} NUMERICAL SUMMARY")

    display(df.describe().T)

PRODUCTS NUMERICAL SUMMARY

,count,mean,std,min,25%,50%,75%,max
Base_List_Price_INR,240.00,"1,976.92","3,269.60",199.00,599.00,"1,049.00","2,199.00","28,899.00"
Base_Unit_Cost_INR,240.00,"1,175.62","1,996.99",110.00,351.25,606.00,"1,292.00","18,997.00"

SALES NUMERICAL SUMMARY

,count,mean,std,min,25%,50%,75%,max
Order_Hour,"84,000.00",16.76,3.38,7.00,14.00,17.00,19.00,23.00
Quantity,"84,000.00",1.26,0.55,1.00,1.00,1.00,1.00,4.00
Unit_List_Price_INR,"84,000.00","1,264.42","1,684.73",199.00,499.00,799.00,"1,499.00","29,765.97"
Unit_Cost_INR,"84,000.00",745.90,"1,011.89",110.00,274.00,463.30,871.00,"19,471.93"
Gross_Sales_INR,"84,000.00","1,542.29","1,947.79",199.00,598.00,925.97,"1,799.00","29,765.97"
Discount_INR,"84,000.00",51.13,148.22,0.00,0.00,0.00,41.15,"4,334.85"
Sales_Before_Returns_INR,"84,000.00","1,491.16","1,889.79",159.20,513.97,899.00,"1,759.34","29,765.97"
Returned_Qty,"84,000.00",0.04,0.22,0.00,0.00,0.00,0.00,4.00
Refund_INR,"84,000.00",50.12,450.49,0.00,0.00,0.00,0.00,"28,899.00"
Net_Sales_INR,"84,000.00","1,441.04","1,868.70",0.00,499.00,822.97,"1,699.00","29,765.97"
Net_COGS_INR,"84,000.00",879.24,"1,152.12",0.00,306.00,524.00,"1,061.90","19,471.93"
Gross_Profit_INR,"84,000.00",561.80,739.01,0.00,183.42,327.90,655.00,"10,629.35"

STORES NUMERICAL SUMMARY

,count,mean,std,min,25%,50%,75%,max
Floor_Area_Sqm,30.00,"3,790.00","1,025.65","1,800.00","3,200.00","3,800.00","4,775.00","5,200.00"

### Explore categorical columns

In [19]:
for name, df in datasets.items():
    categorical_columns = df.select_dtypes(
        include=["object", "category", "string"]
    ).columns

    print(f"\n{name.upper()} CATEGORICAL COLUMNS")

    for column in categorical_columns:
        print(f"\nColumn: {column}")
        print(f"Unique values: {df[column].nunique(dropna=True)}")

        display(
            df[column]
            .value_counts(dropna=False)
            .head(10)
            .rename_axis(column)
            .reset_index(name="Count")
        )

PRODUCTS CATEGORICAL COLUMNS

Column: Product_Key
Unique values: 240

  Product_Key  Count
0       P0001      1
1       P0002      1
2       P0003      1
3       P0004      1
4       P0005      1
5       P0006      1
6       P0007      1
7       P0008      1
8       P0009      1
9       P0010      1

Column: Product_Name
Unique values: 240

                             Product_Name  Count
0    Running Shoes Essential Black (Demo)      1
1     Running Shoes Essential Blue (Demo)      1
2       Running Shoes Active Black (Demo)      1
3        Running Shoes Active Blue (Demo)      1
4  Running Shoes Performance Black (Demo)      1
5   Running Shoes Performance Blue (Demo)      1
6  Running T-Shirt Essential Black (Demo)      1
7   Running T-Shirt Essential Blue (Demo)      1
8     Running T-Shirt Active Black (Demo)      1
9      Running T-Shirt Active Blue (Demo)      1

Column: Sport
Unique values: 10

       Sport  Count
0    Running     24
1     Hiking     24
2    Cycling     24
3    Fitness     24
4   Swimming     24
5   Football     24
6  Badminton     24
7    Cricket     24
8       Yoga     24
9     Tennis     24

Column: Product_Type
Unique values: 40

      Product_Type  Count
0    Running Shoes      6
1  Running T-Shirt      6
2   Running Shorts      6
3    Running Socks      6
4     Hiking Shoes      6
5  Hiking Backpack      6
6      Rain Jacket      6
7     Camping Tent      6
8    Mountain Bike      6
9   Cycling Helmet      6

Column: Brand_Label
Unique values: 10

      Brand_Label  Count
0         Kalenji     24
1         Quechua     24
2       Rockrider     24
3          Domyos     24
4         Nabaiji     24
5          Kipsta     24
6          Perfly     24
7  Sport Practice     24
8         Kimjaly     24
9         Artengo     24

Column: Product_Tier
Unique values: 3

  Product_Tier  Count
0    Essential     80
1       Active     80
2  Performance     80

Column: Colour
Unique values: 2

  Colour  Count
0  Black    120
1   Blue    120

SALES CATEGORICAL COLUMNS

Column: Sale_Line_ID
Unique values: 84000

  Sale_Line_ID  Count
0     SL083984      1
1     SL083983      1
2     SL083982      1
3     SL083981      1
4     SL083980      1
5     SL083979      1
6     SL083978      1
7     SL083977      1
8     SL083976      1
9     SL083975      1

Column: Order_ID
Unique values: 53190

    Order_ID  Count
0  ORD022250      4
1  ORD022251      4
2  ORD053155      4
3  ORD053168      4
4  ORD043429      4
5  ORD022211      4
6  ORD022342      4
7  ORD053096      4
8  ORD053115      4
9  ORD006935      4

Column: Purchase_Date
Unique values: 623

  Purchase_Date  Count
0    2026-08-09    240
1    2026-05-17    235
2    2026-08-22    233
3    2026-01-31    231
4    2025-12-13    230
5    2026-01-03    229
6    2026-01-04    227
7    2025-12-14    227
8    2026-05-16    226
9    2026-06-28    224

Column: Product_ID
Unique values: 240

  Product_ID  Count
0      P0019    850
1      P0091    774
2      P0109    765
3      P0021    742
4      P0022    734
5      P0020    730
6      P0110    685
7      P0093    680
8      P0175    667
9      P0112    653

Column: Store_ID
Unique values: 30

  Store_ID  Count
0     S009   5585
1     S017   5510
2     S002   5505
3     S001   5401
4     S025   5334
5     S013   5297
6     S011   5282
7     S023   2176
8     S007   2115
9     S030   2087

Column: Channel
Unique values: 3

      Channel  Count
0    In Store  56087
1     Website  15875
2  Mobile App  12038

Column: Payment_Method
Unique values: 5

  Payment_Method  Count
0            UPI  48682
1    Credit Card  18524
2     Debit Card  10838
3           Cash   4010
4    Net Banking   1946

Column: Promotion
Unique values: 3

        Promotion  Count
0            None  57131
1  Seasonal Offer  18348
2   Weekend Offer   8521

Column: Discount_Pct
Unique values: 5

  Discount_Pct  Count
0           0%  57131
1          10%  10702
2           5%   8125
3          15%   5914
4          20%   2128

Column: Return_Reason
Unique values: 5

     Return_Reason  Count
0     Not Returned  80957
1    Quality Issue   1010
2     Changed Mind    989
3  Not As Expected    738
4      Size or Fit    306

STORES CATEGORICAL COLUMNS

Column: Store_Key
Unique values: 30

  Store_Key  Count
0      S001      1
1      S002      1
2      S003      1
3      S004      1
4      S005      1
5      S006      1
6      S007      1
7      S008      1
8      S009      1
9      S010      1

Column: Store_Name
Unique values: 30

                    Store_Name  Count
0     Demo Mumbai Sports Store      1
1       Demo Pune Sports Store      1
2     Demo Nashik Sports Store      1
3     Demo Nagpur Sports Store      1
4  Demo Ahmedabad Sports Store      1
5      Demo Surat Sports Store      1
6   Demo Vadodara Sports Store      1
7     Demo Panaji Sports Store      1
8  Demo Bengaluru Sports Store      1
9     Demo Mysuru Sports Store      1

Column: City
Unique values: 30

        City  Count
0     Mumbai      1
1       Pune      1
2     Nashik      1
3     Nagpur      1
4  Ahmedabad      1
5      Surat      1
6   Vadodara      1
7     Panaji      1
8  Bengaluru      1
9     Mysuru      1

Column: State
Unique values: 20

            State  Count
0     Maharashtra      4
1         Gujarat      3
2       Karnataka      2
3      Tamil Nadu      2
4   Uttar Pradesh      2
5          Kerala      2
6  Madhya Pradesh      2
7             Goa      1
8  Andhra Pradesh      1
9           Delhi      1

Column: Region
Unique values: 5

    Region  Count
0     West      8
1    South      8
2    North      8
3     East      4
4  Central      2

Column: Country
Unique values: 1

  Country  Count
0   India     30

Column: Store_Format
Unique values: 2

   Store_Format  Count
0      Standard     22
1  Large Format      8

### Check unique values in identifier columns
This step helps you inspect identifiers without assuming their names in advance.

In [20]:
for name, df in datasets.items():
    print(f"\n{name.upper()} IDENTIFIER COLUMNS")

    identifier_columns = [
        column for column in df.columns
        if any(
            keyword in column.lower()
            for keyword in ["id", "key", "code"]
        )
    ]

    if not identifier_columns:
        print("No obvious identifier columns found.")
        continue

    for column in identifier_columns:
        print(f"\nColumn: {column}")
        print(f"Unique values: {df[column].nunique(dropna=True)}")
        print(f"Missing values: {df[column].isna().sum()}")

        display(df[column].value_counts().head(10))

PRODUCTS IDENTIFIER COLUMNS

Column: Product_Key
Unique values: 240
Missing values: 0

Product_Key
P0001    1
P0002    1
P0003    1
P0004    1
P0005    1
P0006    1
P0007    1
P0008    1
P0009    1
P0010    1
Name: count, dtype: int64

SALES IDENTIFIER COLUMNS

Column: Sale_Line_ID
Unique values: 84000
Missing values: 0

Sale_Line_ID
SL083984    1
SL083983    1
SL083982    1
SL083981    1
SL083980    1
SL083979    1
SL083978    1
SL083977    1
SL083976    1
SL083975    1
Name: count, dtype: int64

Column: Order_ID
Unique values: 53190
Missing values: 0

Order_ID
ORD022250    4
ORD022251    4
ORD053155    4
ORD053168    4
ORD043429    4
ORD022211    4
ORD022342    4
ORD053096    4
ORD053115    4
ORD006935    4
Name: count, dtype: int64

Column: Product_ID
Unique values: 240
Missing values: 0

Product_ID
P0019    850
P0091    774
P0109    765
P0021    742
P0022    734
P0020    730
P0110    685
P0093    680
P0175    667
P0112    653
Name: count, dtype: int64

Column: Store_ID
Unique values: 30
Missing values: 0

Store_ID
S009    5585
S017    5510
S002    5505
S001    5401
S025    5334
S013    5297
S011    5282
S023    2176
S007    2115
S030    2087
Name: count, dtype: int64

STORES IDENTIFIER COLUMNS

Column: Store_Key
Unique values: 30
Missing values: 0

Store_Key
S001    1
S002    1
S003    1
S004    1
S005    1
S006    1
S007    1
S008    1
S009    1
S010    1
Name: count, dtype: int64

### Check potential negative values
Negative values may be valid in some business situations, such as refunds or sales adjustments. This cell only identifies them; it does not change the data.

In [21]:
for name, df in datasets.items():
    numeric_columns = df.select_dtypes(
        include=np.number
    ).columns

    print(f"\n{name.upper()} NEGATIVE VALUE CHECK")

    found_negative = False

    for column in numeric_columns:
        negative_count = (df[column] < 0).sum()

        if negative_count > 0:
            found_negative = True
            print(
                f"{column}: {negative_count:,} negative values"
            )

    if not found_negative:
        print("No negative values found in numeric columns.")

PRODUCTS NEGATIVE VALUE CHECK
No negative values found in numeric columns.

SALES NEGATIVE VALUE CHECK
No negative values found in numeric columns.

STORES NEGATIVE VALUE CHECK
No negative values found in numeric columns.

### Check date columns
This cell detects columns whose names suggest they contain dates or timestamps. It does not permanently change the original DataFrames.

In [22]:
for name, df in datasets.items():
    print(f"\n{name.upper()} DATE COLUMN CHECK")

    date_columns = [
        column for column in df.columns
        if any(
            keyword in column.lower()
            for keyword in ["date", "time"]
        )
    ]

    if not date_columns:
        print("No obvious date or time columns found.")
        continue

    for column in date_columns:
        converted_dates = pd.to_datetime(
            df[column],
            errors="coerce"
        )

        invalid_count = (
            df[column].notna() & converted_dates.isna()
        ).sum()

        print(f"\nColumn: {column}")
        print(f"Original data type: {df[column].dtype}")
        print(f"Missing values: {df[column].isna().sum()}")
        print(f"Unparseable non-missing values: {invalid_count}")

        valid_dates = converted_dates.dropna()

        if not valid_dates.empty:
            print(f"Earliest date: {valid_dates.min()}")
            print(f"Latest date: {valid_dates.max()}")

PRODUCTS DATE COLUMN CHECK
No obvious date or time columns found.

SALES DATE COLUMN CHECK

Column: Purchase_Date
Original data type: object
Missing values: 0
Unparseable non-missing values: 0
Earliest date: 2025-01-01 00:00:00
Latest date: 2026-09-15 00:00:00

STORES DATE COLUMN CHECK
No obvious date or time columns found.

### Check likely business-value columns
For the Decathlon sales dataset, we should investigate prices, costs, quantities, discounts, and revenue if those columns exist.

In [23]:
for name, df in datasets.items():
    print(f"\n{name.upper()} BUSINESS VALUE CHECK")

    keywords = [
        "price",
        "cost",
        "quantity",
        "discount",
        "revenue",
        "sales",
        "profit",
        "amount"
    ]

    candidate_columns = [
        column for column in df.columns
        if any(
            keyword in column.lower()
            for keyword in keywords
        )
    ]

    if not candidate_columns:
        print("No obvious business-value columns found.")
        continue

    for column in candidate_columns:
        print(f"\nColumn: {column}")
        print(f"Data type: {df[column].dtype}")
        print(f"Missing values: {df[column].isna().sum()}")

        numeric_values = pd.to_numeric(
            df[column],
            errors="coerce"
        )

        if numeric_values.notna().any():
            print(f"Minimum: {numeric_values.min()}")
            print(f"Maximum: {numeric_values.max()}")

PRODUCTS BUSINESS VALUE CHECK

Column: Base_List_Price_INR
Data type: float64
Missing values: 0
Minimum: 199.0
Maximum: 28899.0

Column: Base_Unit_Cost_INR
Data type: float64
Missing values: 0
Minimum: 110.0
Maximum: 18997.0

SALES BUSINESS VALUE CHECK

Column: Quantity
Data type: int64
Missing values: 0
Minimum: 1
Maximum: 4

Column: Unit_List_Price_INR
Data type: float64
Missing values: 0
Minimum: 199.0
Maximum: 29765.970703125

Column: Unit_Cost_INR
Data type: float64
Missing values: 0
Minimum: 110.0
Maximum: 19471.9296875

Column: Discount_Pct
Data type: object
Missing values: 0

Column: Gross_Sales_INR
Data type: float64
Missing values: 0
Minimum: 199.0
Maximum: 29765.970703125

Column: Discount_INR
Data type: float64
Missing values: 0
Minimum: 0.0
Maximum: 4334.85009765625

Column: Sales_Before_Returns_INR
Data type: float64
Missing values: 0
Minimum: 159.1999969482422
Maximum: 29765.970703125

Column: Net_Sales_INR
Data type: float64
Missing values: 0
Minimum: 0.0
Maximum: 29765.970703125

Column: Gross_Profit_INR
Data type: float64
Missing values: 0
Minimum: 0.0
Maximum: 10629.349609375

STORES BUSINESS VALUE CHECK
No obvious business-value columns found.

### Explore sales by product, if the relevant columns exist

The following cell checks whether your sales and products tables share an obvious product identifier. It then uses the available column names to summarize sales by product.

In [24]:
def find_matching_column(df, candidates):
    column_lookup = {
        column.lower(): column
        for column in df.columns
    }

    for candidate in candidates:
        if candidate.lower() in column_lookup:
            return column_lookup[candidate.lower()]

    return None


sales_product_key = find_matching_column(
    sales_df,
    ["Product_ID", "Product_Key", "ProductID", "ProductKey"]
)

products_product_key = find_matching_column(
    products_df,
    ["Product_ID", "Product_Key", "ProductID", "ProductKey"]
)

quantity_column = find_matching_column(
    sales_df,
    ["Quantity", "Units_Sold", "Units"]
)

revenue_column = find_matching_column(
    sales_df,
    ["Gross_Sales_INR", "Revenue", "Sales_Amount", "Total_Sales"]
)

product_name_column = find_matching_column(
    products_df,
    ["Product_Name", "ProductName", "Name"]
)

if sales_product_key and products_product_key:
    print("Potential product key found.")
    print("Sales key:", sales_product_key)
    print("Products key:", products_product_key)

    if quantity_column or revenue_column:
        sales_columns = [sales_product_key]

        if quantity_column:
            sales_columns.append(quantity_column)

        if revenue_column:
            sales_columns.append(revenue_column)

        product_sales = sales_df[sales_columns].copy()

        product_sales = product_sales.merge(
            products_df[
                [products_product_key]
                + ([product_name_column] if product_name_column else [])
            ].drop_duplicates(),
            left_on=sales_product_key,
            right_on=products_product_key,
            how="left",
            indicator=True
        )

        group_columns = [sales_product_key]

        if product_name_column:
            group_columns.append(product_name_column)

        aggregations = {}

        if quantity_column:
            aggregations[quantity_column] = "sum"

        if revenue_column:
            aggregations[revenue_column] = "sum"

        product_summary = (
            product_sales
            .groupby(group_columns, dropna=False)
            .agg(aggregations)
            .reset_index()
            .sort_values(
                by=list(aggregations.keys())[0],
                ascending=False
            )
        )

        display(product_summary.head(10))

        unmatched_count = (
            product_sales["_merge"] == "left_only"
        ).sum()

        print("Sales rows without a matching product:", unmatched_count)

    else:
        print(
            "A product key exists, but no recognized quantity "
            "or revenue column was found."
        )
else:
    print(
        "Could not identify matching product keys automatically. "
        "Review the column names and database relationships."
    )

Potential product key found.
Sales key: Product_ID
Products key: Product_Key

,Product_ID,Product_Name,Quantity,Gross_Sales_INR
18,P0019,Running Socks Essential Black (Demo),1062,"214,287.18"
90,P0091,Resistance Band Essential Black (Demo),975,"295,803.69"
108,P0109,Swimming Cap Essential Black (Demo),969,"195,529.44"
21,P0022,Running Socks Active Blue (Demo),944,"286,292.50"
20,P0021,Running Socks Active Black (Demo),928,"281,015.15"
19,P0020,Running Socks Essential Blue (Demo),926,"280,650.37"
92,P0093,Resistance Band Active Black (Demo),876,"354,407.76"
109,P0110,Swimming Cap Essential Blue (Demo),872,"264,692.74"
174,P0175,Cricket Ball Essential Black (Demo),844,"255,692.84"
110,P0111,Swimming Cap Active Black (Demo),831,"252,272.28"

Sales rows without a matching product: 0

### Check possible relationships between sales and stores

In [25]:
sales_store_key = find_matching_column(
    sales_df,
    ["Store_ID", "Store_Key", "StoreID", "StoreKey"]
)

store_key = find_matching_column(
    store_df,
    ["Store_ID", "Store_Key", "StoreID", "StoreKey"]
)

if sales_store_key and store_key:
    print("Potential store relationship found.")
    print("Sales table key:", sales_store_key)
    print("Store table key:", store_key)

    store_keys = store_df[store_key].dropna().unique()

    unmatched_sales = ~sales_df[sales_store_key].isin(store_keys)

    print(
        "Sales rows with no matching store:",
        int(unmatched_sales.sum())
    )

    print(
        "Distinct store identifiers in sales:",
        sales_df[sales_store_key].nunique(dropna=True)
    )

    print(
        "Distinct store identifiers in store table:",
        store_df[store_key].nunique(dropna=True)
    )
else:
    print(
        "Could not identify matching store keys automatically. "
        "Review the column names and database relationships."
    )

Potential store relationship found.
Sales table key: Store_ID
Store table key: Store_Key
Sales rows with no matching store: 0
Distinct store identifiers in sales: 30
Distinct store identifiers in store table: 30

### Build a data quality summary
This cell creates one summary table showing the overall data quality of each dataset.

In [26]:
quality_results = []

for name, df in datasets.items():
    total_cells = df.shape[0] * df.shape[1]
    missing_cells = int(df.isna().sum().sum())

    quality_results.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing_Cells": missing_cells,
        "Missing_Percentage": (
            missing_cells / total_cells * 100
            if total_cells > 0
            else 0
        ),
        "Duplicate_Rows": int(df.duplicated().sum())
    })

quality_summary = pd.DataFrame(quality_results)

display(quality_summary)

    Dataset   Rows  Columns  Missing_Cells  Missing_Percentage  Duplicate_Rows
0  Products    240        9              0                0.00               0
1     Sales  84000       22              0                0.00               0
2    Stores     30        8              0                0.00               0

### Save the exploration summaries

In [27]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
REPORTS_DIR = PROJECT_ROOT / "reports"

REPORTS_DIR.mkdir(parents=True, exist_ok=True)

quality_summary.to_csv(
    REPORTS_DIR / "data_quality_summary.csv",
    index=False
)

for name, df in datasets.items():
    column_summary = pd.DataFrame({
        "Column": df.columns,
        "Data_Type": df.dtypes.astype(str).values,
        "Non_Null_Count": df.notna().sum().values,
        "Missing_Count": df.isna().sum().values,
        "Unique_Values": [
            df[column].nunique(dropna=True)
            for column in df.columns
        ]
    })

    file_name = name.lower() + "_column_summary.csv"

    column_summary.to_csv(
        REPORTS_DIR / file_name,
        index=False
    )

print("Exploration summaries saved to:", REPORTS_DIR)

Exploration summaries saved to: c:\Users\nasir\OneDrive\Desktop\Portfolio Projects\Decathlon-Data-Analytics\reports

### Close the database connection

In [28]:
conn.close()

print("SQL Server connection closed.")

SQL Server connection closed.

### Summary
1.	Loaded the three SQL Server tables into Pandas. 
2.	Examined the dataset sizes, columns, and data types. 
3.	Checked missing values and duplicate rows. 
4.	Reviewed numerical and categorical data. 
5.	Investigated potential invalid values and date issues. 
6.	Performed preliminary checks of product and store relationships. 
7.	Created data quality and column-summary reports.